/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export declare namespace SmartPay {
  export type SignatureStruct = {
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type SignatureStructOutput = [number, string, string] & {
    v: number;
    r: string;
    s: string;
  };
}

export interface SmartPayInterface extends utils.Interface {
  functions: {
    "FIXED_SUBSCRIPTION_TYPEHASH()": FunctionFragment;
    "createSubscription(address,uint256,uint256,uint256,bytes32,uint8,(uint8,bytes32,bytes32))": FunctionFragment;
    "hashSubscription(address,address,uint256,uint256,uint256,bytes32,uint8)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "processPayment(address,address,uint256,uint256,uint256,bytes32,uint8)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "subscriptions(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "FIXED_SUBSCRIPTION_TYPEHASH"
      | "createSubscription"
      | "hashSubscription"
      | "owner"
      | "pause"
      | "paused"
      | "processPayment"
      | "renounceOwnership"
      | "subscriptions"
      | "transferOwnership"
      | "unpause"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "FIXED_SUBSCRIPTION_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      SmartPay.SignatureStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hashSubscription",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPayment",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "FIXED_SUBSCRIPTION_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "SubscriptionCreated(address,uint256,address,uint256,uint256,uint256,bytes32,uint8)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SubscriptionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface SubscriptionCreatedEventObject {
  subscriber: string;
  subscriptionId: BigNumber;
  paymentToken: string;
  paymentAmount: BigNumber;
  startTime: BigNumber;
  totalPayments: BigNumber;
  paymentReference: string;
  cadence: number;
}
export type SubscriptionCreatedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber, BigNumber, string, number],
  SubscriptionCreatedEventObject
>;

export type SubscriptionCreatedEventFilter =
  TypedEventFilter<SubscriptionCreatedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface SmartPay extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SmartPayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    FIXED_SUBSCRIPTION_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    createSubscription(
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      signature: SmartPay.SignatureStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hashSubscription(
      subscriber: PromiseOrValue<string>,
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    processPayment(
      subscriber: PromiseOrValue<string>,
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subscriptions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        paymentCount: BigNumber;
        startTime: BigNumber;
        totalPayments: BigNumber;
        lastPaymentTimestamp: BigNumber;
      }
    >;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  FIXED_SUBSCRIPTION_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  createSubscription(
    paymentToken: PromiseOrValue<string>,
    paymentAmount: PromiseOrValue<BigNumberish>,
    startTime: PromiseOrValue<BigNumberish>,
    totalPayments: PromiseOrValue<BigNumberish>,
    paymentReference: PromiseOrValue<BytesLike>,
    cadence: PromiseOrValue<BigNumberish>,
    signature: SmartPay.SignatureStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hashSubscription(
    subscriber: PromiseOrValue<string>,
    paymentToken: PromiseOrValue<string>,
    paymentAmount: PromiseOrValue<BigNumberish>,
    startTime: PromiseOrValue<BigNumberish>,
    totalPayments: PromiseOrValue<BigNumberish>,
    paymentReference: PromiseOrValue<BytesLike>,
    cadence: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  processPayment(
    subscriber: PromiseOrValue<string>,
    paymentToken: PromiseOrValue<string>,
    paymentAmount: PromiseOrValue<BigNumberish>,
    startTime: PromiseOrValue<BigNumberish>,
    totalPayments: PromiseOrValue<BigNumberish>,
    paymentReference: PromiseOrValue<BytesLike>,
    cadence: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subscriptions(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      paymentCount: BigNumber;
      startTime: BigNumber;
      totalPayments: BigNumber;
      lastPaymentTimestamp: BigNumber;
    }
  >;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    FIXED_SUBSCRIPTION_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    createSubscription(
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      signature: SmartPay.SignatureStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    hashSubscription(
      subscriber: PromiseOrValue<string>,
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    processPayment(
      subscriber: PromiseOrValue<string>,
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    subscriptions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        paymentCount: BigNumber;
        startTime: BigNumber;
        totalPayments: BigNumber;
        lastPaymentTimestamp: BigNumber;
      }
    >;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "SubscriptionCreated(address,uint256,address,uint256,uint256,uint256,bytes32,uint8)"(
      subscriber?: PromiseOrValue<string> | null,
      subscriptionId?: PromiseOrValue<BigNumberish> | null,
      paymentToken?: PromiseOrValue<string> | null,
      paymentAmount?: null,
      startTime?: null,
      totalPayments?: null,
      paymentReference?: null,
      cadence?: null
    ): SubscriptionCreatedEventFilter;
    SubscriptionCreated(
      subscriber?: PromiseOrValue<string> | null,
      subscriptionId?: PromiseOrValue<BigNumberish> | null,
      paymentToken?: PromiseOrValue<string> | null,
      paymentAmount?: null,
      startTime?: null,
      totalPayments?: null,
      paymentReference?: null,
      cadence?: null
    ): SubscriptionCreatedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    FIXED_SUBSCRIPTION_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    createSubscription(
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      signature: SmartPay.SignatureStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hashSubscription(
      subscriber: PromiseOrValue<string>,
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    processPayment(
      subscriber: PromiseOrValue<string>,
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subscriptions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    FIXED_SUBSCRIPTION_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createSubscription(
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      signature: SmartPay.SignatureStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hashSubscription(
      subscriber: PromiseOrValue<string>,
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    processPayment(
      subscriber: PromiseOrValue<string>,
      paymentToken: PromiseOrValue<string>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      totalPayments: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      cadence: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subscriptions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
