/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface SpritzInterface extends utils.Interface {
  functions: {
    "owner()": FunctionFragment;
    "payWithSwap(address,address,uint256,address,uint256,address,address,bytes,bytes32)": FunctionFragment;
    "payWithToken(address,address,uint256,bytes32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "owner"
      | "payWithSwap"
      | "payWithToken"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payWithSwap",
    values: [
      string,
      string,
      BigNumberish,
      string,
      BigNumberish,
      string,
      string,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payWithToken",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payWithSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payWithToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "Payment(address,uint256,address,uint256,address,address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Payment"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PaymentEventObject {
  sourceToken: string;
  sourceTokenAmount: BigNumber;
  paymentToken: string;
  paymentTokenAmount: BigNumber;
  from: string;
  to: string;
  paymentReference: string;
}
export type PaymentEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, string, string, string],
  PaymentEventObject
>;

export type PaymentEventFilter = TypedEventFilter<PaymentEvent>;

export interface Spritz extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SpritzInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    owner(overrides?: CallOverrides): Promise<[string]>;

    payWithSwap(
      to: string,
      sourceTokenAddress: string,
      sourceTokenAmount: BigNumberish,
      paymentTokenAddress: string,
      paymentTokenAmount: BigNumberish,
      allowanceTarget: string,
      swapTarget: string,
      swapCallData: BytesLike,
      paymentReference: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    payWithToken(
      to: string,
      paymentTokenAddress: string,
      paymentTokenAmount: BigNumberish,
      paymentReference: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  owner(overrides?: CallOverrides): Promise<string>;

  payWithSwap(
    to: string,
    sourceTokenAddress: string,
    sourceTokenAmount: BigNumberish,
    paymentTokenAddress: string,
    paymentTokenAmount: BigNumberish,
    allowanceTarget: string,
    swapTarget: string,
    swapCallData: BytesLike,
    paymentReference: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  payWithToken(
    to: string,
    paymentTokenAddress: string,
    paymentTokenAmount: BigNumberish,
    paymentReference: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    owner(overrides?: CallOverrides): Promise<string>;

    payWithSwap(
      to: string,
      sourceTokenAddress: string,
      sourceTokenAmount: BigNumberish,
      paymentTokenAddress: string,
      paymentTokenAmount: BigNumberish,
      allowanceTarget: string,
      swapTarget: string,
      swapCallData: BytesLike,
      paymentReference: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    payWithToken(
      to: string,
      paymentTokenAddress: string,
      paymentTokenAmount: BigNumberish,
      paymentReference: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "Payment(address,uint256,address,uint256,address,address,bytes32)"(
      sourceToken?: null,
      sourceTokenAmount?: null,
      paymentToken?: null,
      paymentTokenAmount?: null,
      from?: null,
      to?: null,
      paymentReference?: null
    ): PaymentEventFilter;
    Payment(
      sourceToken?: null,
      sourceTokenAmount?: null,
      paymentToken?: null,
      paymentTokenAmount?: null,
      from?: null,
      to?: null,
      paymentReference?: null
    ): PaymentEventFilter;
  };

  estimateGas: {
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    payWithSwap(
      to: string,
      sourceTokenAddress: string,
      sourceTokenAmount: BigNumberish,
      paymentTokenAddress: string,
      paymentTokenAmount: BigNumberish,
      allowanceTarget: string,
      swapTarget: string,
      swapCallData: BytesLike,
      paymentReference: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    payWithToken(
      to: string,
      paymentTokenAddress: string,
      paymentTokenAmount: BigNumberish,
      paymentReference: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payWithSwap(
      to: string,
      sourceTokenAddress: string,
      sourceTokenAmount: BigNumberish,
      paymentTokenAddress: string,
      paymentTokenAmount: BigNumberish,
      allowanceTarget: string,
      swapTarget: string,
      swapCallData: BytesLike,
      paymentReference: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    payWithToken(
      to: string,
      paymentTokenAddress: string,
      paymentTokenAmount: BigNumberish,
      paymentReference: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
