/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IAnyswapV4Router,
  IAnyswapV4RouterInterface,
} from "../../../contracts/interfaces/IAnyswapV4Router";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "anySwapOut",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "anySwapOutUnderlying",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAnyswapV4Router__factory {
  static readonly abi = _abi;
  static createInterface(): IAnyswapV4RouterInterface {
    return new utils.Interface(_abi) as IAnyswapV4RouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAnyswapV4Router {
    return new Contract(address, _abi, signerOrProvider) as IAnyswapV4Router;
  }
}
