/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export declare namespace ISpritzSwapModule {
  export type ExactOutputParamsStruct = {
    to: PromiseOrValue<string>;
    from: PromiseOrValue<string>;
    inputTokenAmountMax: PromiseOrValue<BigNumberish>;
    paymentTokenAmount: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
    swapData: PromiseOrValue<BytesLike>;
  };

  export type ExactOutputParamsStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    to: string;
    from: string;
    inputTokenAmountMax: BigNumber;
    paymentTokenAmount: BigNumber;
    deadline: BigNumber;
    swapData: string;
  };
}

export interface SpritzV3SwapModuleInterface extends utils.Interface {
  functions: {
    "decodeSwapData(bytes)": FunctionFragment;
    "exactOutputNativeSwap((address,address,uint256,uint256,uint256,bytes))": FunctionFragment;
    "exactOutputSwap((address,address,uint256,uint256,uint256,bytes))": FunctionFragment;
    "swapTarget()": FunctionFragment;
    "weth()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "decodeSwapData"
      | "exactOutputNativeSwap"
      | "exactOutputSwap"
      | "swapTarget"
      | "weth"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "decodeSwapData",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputNativeSwap",
    values: [ISpritzSwapModule.ExactOutputParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputSwap",
    values: [ISpritzSwapModule.ExactOutputParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTarget",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "decodeSwapData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputNativeSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapTarget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;

  events: {};
}

export interface SpritzV3SwapModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SpritzV3SwapModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    decodeSwapData(
      swapData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & {
        inputTokenAddress: string;
        outputTokenAddress: string;
      }
    >;

    exactOutputNativeSwap(
      swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    exactOutputSwap(
      swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapTarget(overrides?: CallOverrides): Promise<[string]>;

    weth(overrides?: CallOverrides): Promise<[string]>;
  };

  decodeSwapData(
    swapData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [string, string] & { inputTokenAddress: string; outputTokenAddress: string }
  >;

  exactOutputNativeSwap(
    swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  exactOutputSwap(
    swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapTarget(overrides?: CallOverrides): Promise<string>;

  weth(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    decodeSwapData(
      swapData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & {
        inputTokenAddress: string;
        outputTokenAddress: string;
      }
    >;

    exactOutputNativeSwap(
      swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactOutputSwap(
      swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapTarget(overrides?: CallOverrides): Promise<string>;

    weth(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    decodeSwapData(
      swapData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactOutputNativeSwap(
      swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    exactOutputSwap(
      swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapTarget(overrides?: CallOverrides): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    decodeSwapData(
      swapData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    exactOutputNativeSwap(
      swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    exactOutputSwap(
      swapParams: ISpritzSwapModule.ExactOutputParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapTarget(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
