/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SpritzPayStorage__factory } from "./SpritzPayStorage__factory";
export { SpritzPayStorageV2__factory } from "./SpritzPayStorageV2__factory";
