/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface SpritzPay_V1Interface extends utils.Interface {
  functions: {
    "initialize(address,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "payWithNative(address,address,address,uint256,uint256,bytes,bytes32)": FunctionFragment;
    "payWithSwap(address,address,address,uint256,uint256,bytes,bytes32)": FunctionFragment;
    "payWithToken(address,address,uint256,bytes32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "swapRouter()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "initialize"
      | "owner"
      | "payWithNative"
      | "payWithSwap"
      | "payWithToken"
      | "renounceOwnership"
      | "swapRouter"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payWithNative",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payWithSwap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payWithToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payWithNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payWithSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payWithToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Payment(address,address,address,uint256,address,uint256,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Payment"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PaymentEventObject {
  to: string;
  from: string;
  sourceToken: string;
  sourceTokenAmount: BigNumber;
  paymentToken: string;
  paymentTokenAmount: BigNumber;
  paymentReference: string;
}
export type PaymentEvent = TypedEvent<
  [string, string, string, BigNumber, string, BigNumber, string],
  PaymentEventObject
>;

export type PaymentEventFilter = TypedEventFilter<PaymentEvent>;

export interface SpritzPay_V1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SpritzPay_V1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    initialize(
      _swapRouterAddress: PromiseOrValue<string>,
      _wrappedEtherAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    payWithNative(
      _to: PromiseOrValue<string>,
      _sourceTokenAddress: PromiseOrValue<string>,
      _paymentTokenAddress: PromiseOrValue<string>,
      _paymentTokenAmount: PromiseOrValue<BigNumberish>,
      _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
      _path: PromiseOrValue<BytesLike>,
      _paymentReference: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    payWithSwap(
      _to: PromiseOrValue<string>,
      _sourceTokenAddress: PromiseOrValue<string>,
      _paymentTokenAddress: PromiseOrValue<string>,
      _paymentTokenAmount: PromiseOrValue<BigNumberish>,
      _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
      _path: PromiseOrValue<BytesLike>,
      _paymentReference: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    payWithToken(
      to: PromiseOrValue<string>,
      paymentTokenAddress: PromiseOrValue<string>,
      paymentTokenAmount: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  initialize(
    _swapRouterAddress: PromiseOrValue<string>,
    _wrappedEtherAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  payWithNative(
    _to: PromiseOrValue<string>,
    _sourceTokenAddress: PromiseOrValue<string>,
    _paymentTokenAddress: PromiseOrValue<string>,
    _paymentTokenAmount: PromiseOrValue<BigNumberish>,
    _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
    _path: PromiseOrValue<BytesLike>,
    _paymentReference: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  payWithSwap(
    _to: PromiseOrValue<string>,
    _sourceTokenAddress: PromiseOrValue<string>,
    _paymentTokenAddress: PromiseOrValue<string>,
    _paymentTokenAmount: PromiseOrValue<BigNumberish>,
    _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
    _path: PromiseOrValue<BytesLike>,
    _paymentReference: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  payWithToken(
    to: PromiseOrValue<string>,
    paymentTokenAddress: PromiseOrValue<string>,
    paymentTokenAmount: PromiseOrValue<BigNumberish>,
    paymentReference: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      _swapRouterAddress: PromiseOrValue<string>,
      _wrappedEtherAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    payWithNative(
      _to: PromiseOrValue<string>,
      _sourceTokenAddress: PromiseOrValue<string>,
      _paymentTokenAddress: PromiseOrValue<string>,
      _paymentTokenAmount: PromiseOrValue<BigNumberish>,
      _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
      _path: PromiseOrValue<BytesLike>,
      _paymentReference: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    payWithSwap(
      _to: PromiseOrValue<string>,
      _sourceTokenAddress: PromiseOrValue<string>,
      _paymentTokenAddress: PromiseOrValue<string>,
      _paymentTokenAmount: PromiseOrValue<BigNumberish>,
      _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
      _path: PromiseOrValue<BytesLike>,
      _paymentReference: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    payWithToken(
      to: PromiseOrValue<string>,
      paymentTokenAddress: PromiseOrValue<string>,
      paymentTokenAmount: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    swapRouter(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Payment(address,address,address,uint256,address,uint256,bytes32)"(
      to?: null,
      from?: null,
      sourceToken?: null,
      sourceTokenAmount?: null,
      paymentToken?: null,
      paymentTokenAmount?: null,
      paymentReference?: null
    ): PaymentEventFilter;
    Payment(
      to?: null,
      from?: null,
      sourceToken?: null,
      sourceTokenAmount?: null,
      paymentToken?: null,
      paymentTokenAmount?: null,
      paymentReference?: null
    ): PaymentEventFilter;
  };

  estimateGas: {
    initialize(
      _swapRouterAddress: PromiseOrValue<string>,
      _wrappedEtherAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    payWithNative(
      _to: PromiseOrValue<string>,
      _sourceTokenAddress: PromiseOrValue<string>,
      _paymentTokenAddress: PromiseOrValue<string>,
      _paymentTokenAmount: PromiseOrValue<BigNumberish>,
      _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
      _path: PromiseOrValue<BytesLike>,
      _paymentReference: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    payWithSwap(
      _to: PromiseOrValue<string>,
      _sourceTokenAddress: PromiseOrValue<string>,
      _paymentTokenAddress: PromiseOrValue<string>,
      _paymentTokenAmount: PromiseOrValue<BigNumberish>,
      _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
      _path: PromiseOrValue<BytesLike>,
      _paymentReference: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    payWithToken(
      to: PromiseOrValue<string>,
      paymentTokenAddress: PromiseOrValue<string>,
      paymentTokenAmount: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      _swapRouterAddress: PromiseOrValue<string>,
      _wrappedEtherAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payWithNative(
      _to: PromiseOrValue<string>,
      _sourceTokenAddress: PromiseOrValue<string>,
      _paymentTokenAddress: PromiseOrValue<string>,
      _paymentTokenAmount: PromiseOrValue<BigNumberish>,
      _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
      _path: PromiseOrValue<BytesLike>,
      _paymentReference: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    payWithSwap(
      _to: PromiseOrValue<string>,
      _sourceTokenAddress: PromiseOrValue<string>,
      _paymentTokenAddress: PromiseOrValue<string>,
      _paymentTokenAmount: PromiseOrValue<BigNumberish>,
      _sourceTokenAmountMax: PromiseOrValue<BigNumberish>,
      _path: PromiseOrValue<BytesLike>,
      _paymentReference: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    payWithToken(
      to: PromiseOrValue<string>,
      paymentTokenAddress: PromiseOrValue<string>,
      paymentTokenAmount: PromiseOrValue<BigNumberish>,
      paymentReference: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
